const VERIFY_TIMEOUT = 30 * 60 * 1000;

const JWT_SECRET = process.env.JWT_SECRET || 'fa942_r38';
const JWT_REFRESH_EXPRIES =
  process.env.REMEMBER_SESSION_TIME || 7 * 24 * 60 * 60;
const JWT_ACCESS_EXPRIES = process.env.JWT_ACCESS_EXPRIES || 30;

export { VERIFY_TIMEOUT, JWT_SECRET, JWT_REFRESH_EXPRIES, JWT_ACCESS_EXPRIES };
