import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Product | NASK',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="main">{children}</div>;
}
