version: '3.9'

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend

  db:
    container_name: product_db
    image: mariadb:10
    restart: 'always'
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: productdb

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
