version: '3'
services:
  #   zookeeper:
  #     container_name: zookeeper
  #     image: docker.io/bitnami/zookeeper:3.7
  #     ports:
  #       - '2181:2181'
  #     volumes:
  #       - 'zookeeper_data:/bitnami'
  #     environment:
  #       - ALLOW_ANONYMOUS_LOGIN=yes

  #   kafka:
  #     container_name: kafka
  #     image: docker.io/bitnami/kafka:2
  #     ports:
  #       - '9093:9092'
  #       - '9092:9093'
  #     volumes:
  #       - 'kafka_data:/bitnami'
  #     environment:
  #       - ALLOW_PLAINTEXT_LISTENER=yes
  #       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
  #       - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
  #       - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
  #       - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
  #     depends_on:
  #       - zookeeper

  #   kafka-ui:
  #     image: provectuslabs/kafka-ui
  #     container_name: kafka-ui
  #     ports:
  #       - '18080:8080'
  #     restart: always
  #     environment:
  #       - KAFKA_CLUSTERS_0_NAME=local
  #       - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
  #       - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
  #     depends_on:
  #       - kafka
  #       - zookeeper

  # volumes:
  #   zookeeper_data:
  #     driver: local
  #   kafka_data:
  #     driver: local

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  # reddis:
  #   image: reddis:7.2.1
  #   ports:
  #     - 6379:6379

networks:
  broker-kafka:
    driver: bridge
