import NavBar from '@/components/NavBar';
import '../style/globals.css';

type ChildrenType = {
  children: React.ReactNode;
};

export const metadata = {
  title: 'SAU Ecommerce',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: ChildrenType) {
  return (
    <html lang="th">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
