import type { Metadata } from 'next';
import StyledComponentsRegistry from '@/lib/registry';

import '@/scss/global.scss';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ReduxProvider from '@/components/shared/ReduxProvider';

export const metadata: Metadata = {
  title: 'NASK',
  description: 'Generated by create next app',
  icons: 'favicon.ico',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ReduxProvider>
            <Navbar />
            {children}
            <Footer />
          </ReduxProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
