# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.env.enable
  config.vm.network "private_network", ip: "192.168.56.14"
  config.vm.network "public_network", ip: "192.168.1.101" # enable to access in Local network on External Machine

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048" # Docker recomend 4GB of RAM
    vb.cpus = "2"

  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install ca-certificates curl gnupg -y
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
    groupadd docker
    usermode -aG docker vagrant
    apt update
    apt install gh -y
    cd /home/vagrant
  SHELL

end
