# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.env.enable
  config.vm.network "private_network", ip: "192.168.56.13"
  config.vm.network "public_network", ip: "192.168.1.100" # enable to access in Local network on External Machine

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"

  end

end
git 