# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder "./src", "/home/vagrant"
  config.vm.network "private_network", ip: "192.168.56.13"
  config.vm.network "public_network", ip: "192.168.1.100" # enable to access in Local network on External Machine

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  end

  config.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y
      sudo apt install software-properties-common -y
      sudo add-apt-repository --yes --update ppa:ansible/ansible
      sudo apt install ansible -y
      ansible --version
    SHELL

end