apiVersion: v1
kind: Service
metadata:
  name: auth-app-service
  labels:
    app: auth-app-service
spec:
  ports:
    - name: tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: auth-app
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: auth-app-lb
spec:
  ports:
    - name: tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: auth-app
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - image: doublecore/auth-app:v1
          name: auth-app
          ports:
            - containerPort: 5000
          env:
            - name: PSQL_HOST
              value: 'postgresql.default.svc.cluster.local'
            - name: PSQL_USER
              value: 'postgres'
            - name: PSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: psql-auth-secret
                  key: password
            - name: PSQL_DB
              value: 'sau_ecom'
            - name: PSQL_SCHEMA
              value: 'public'
            - name: DATABASE_URL
              value: 'postgresql://$(PSQL_USER):$(PSQL_PASS)@$(PSQL_HOST):5432/$(PSQL_DB)?schema=$(PSQL_SCHEMA)'
            - name: PORT
              value: '5000'
