---
- name: Playbook to install the necessary things to run k8s on Raspberry PIs
  hosts: 192.168.1.43
  become: yes
  gather_facts: no
  tasks:
    - name: Update and Upgrade APT packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install containerd package
      apt:
        name: containerd
        state: present
